# Generated by Django 4.1.2 on 2022-10-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
        migrations.RemoveField(
            model_name="user",
            name="dob",
        ),
        migrations.AddField(
            model_name="user",
            name="_role",
            field=models.SmallIntegerField(
                choices=[(1, "ADMINISTRATOR"), (2, "MANAGER"), (3, "DEVELOPER")],
                default=3,
                help_text="The role of the user.",
                verbose_name="Role",
            ),
        ),
    ]
