# Generated by Django 4.1.2 on 2022-10-23 11:15

import common.model_mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Public ID unique to each project",
                        max_length=30,
                        unique=True,
                        verbose_name="Public Project ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the project",
                        max_length=50,
                        verbose_name="Project Name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projectss",
                "ordering": ("name",),
            },
            bases=(common.model_mixins.ValidateOnSaveMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Public ID unique to each task",
                        max_length=30,
                        unique=True,
                        verbose_name="Public Course ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the task",
                        max_length=50,
                        verbose_name="Task Name",
                    ),
                ),
                (
                    "due",
                    models.DateField(
                        blank=True,
                        help_text="The date on which the task is due to finish",
                        verbose_name="Due Date",
                    ),
                ),
                (
                    "is_finished",
                    models.BooleanField(
                        blank=True,
                        default=True,
                        help_text="Is the task finished or not",
                        verbose_name="Is finished",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "ordering": ("name",),
            },
            bases=(common.model_mixins.ValidateOnSaveMixin, models.Model),
        ),
    ]
