# Generated by Django 4.1.2 on 2022-10-23 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("task_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="developer",
            field=models.ManyToManyField(
                blank=True,
                help_text="The developer who is sopposed to do the task",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Developer",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                help_text="The project in which this task is defined",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="task_management.project",
                verbose_name="Corresponding Project",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                help_text="Project Manager",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Project Manager",
            ),
        ),
    ]
