# Generated by Django 4.1.2 on 2022-10-26 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("task_management", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="manager",
            field=models.OneToOneField(
                blank=True,
                help_text="Project Manager",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Project Manager",
            ),
        ),
    ]
